---
title: "BQT_Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Reading Data. Data is in .dta format. It would require "foreign" library. Sorry to xenophobes. 

```{r}
library(foreign)
data_main <- read.dta("data.dta")
```

Now, we will drop data points that are not in the range

```{r}
data1 <- data_main[data_main$dist_from_cut > -0.6 & data_main$dist_from_cut < 0.6, ]
```

```{r}
library(qwraps2)

descriptive_summary <- list("Characterisitcs" = list('High School Grade Percentile' =~ qwraps2::mean_sd(hsgrade_pct),
                                                     'Credits Attempted in First Year' =~ qwraps2::mean_sd(totcredits_year1),
                                                     'Age at entry' =~ qwraps2::mean_sd(age_at_entry),
                                                     'male' =~ qwraps2::mean_sd(male),
                                                     'English is First Language' =~ qwraps2::mean_sd(english),
                                                     'Born in North America' =~ qwraps2::mean_sd(bpl_north_america),
                                                     'At Campus 1' =~ qwraps2::mean_sd(loc_campus1),
                                                     'At Campus 2' =~ qwraps2::mean_sd(loc_campus2),
                                                     'At Campus 3' =~ qwraps2::mean_sd(loc_campus3)), 
                            "Outcomes" = list('Distance from Cutoff in 1st Year' =~ qwraps2::mean_sd(dist_from_cut),
                                              'On Probation After 1st Year' =~ qwraps2::mean_sd(probation_year1),
                                              'Ever on Academic Probation' =~ qwraps2::mean_sd(probation_ever),
                                              'Left University after 1st Evaluation' =~ qwraps2::mean_sd(left_school),
                                              'Distance from Cutoff Next Evaluation' =~ qwraps2::mean_sd(nextGPA, na_rm = TRUE, show_n = 'never'),
                                              'Ever Suspended' =~ qwraps2::mean_sd(suspended_ever, na_rm = TRUE, show_n = 'never'),
                                              'Graduated by Year 4' =~ qwraps2::mean_sd(gradin4, na_rm = TRUE, show_n = 'never'),
                                              'Graduated by Year 5' =~ qwraps2::mean_sd(gradin5, na_rm = TRUE, show_n = 'never'),
                                              'Graduated by Year 6' =~ qwraps2::mean_sd(gradin6, na_rm = TRUE, show_n = 'never')))
options(qwraps2_markup = "markdown")
table1 = summary_table(data1, descriptive_summary)
table1
```

#testing for conditions of RDD
```{r}
library(sandwich)
library(lmtest)
library(dplyr)
library(formattable)

val_check = function(x)
{
  model = lm(x ~ gpalscutoff + gpaXgpalscutoff + gpaXgpagrcutoff, data = data1)
  a = coeftest(model, vcov = vcovCL, cluster = data1$clustervar)
  c(a[2,1], a[2, 4], a[2, 2], a[1, 1], a[1, 4], a[1, 2])
}

myvars = c('hsgrade_pct', 'totcredits_year1', 'age_at_entry', 'male', 'english','bpl_north_america','loc_campus1', 'loc_campus2', 'loc_campus3')
chardata <- data1[myvars]
#colnames(abc) = c('gpa below cutoff 1', 'p-value 1', 'sd-error 1', 'intercept 0', 'p value 0', 'sd-error 1')
answer = lapply(chardata, val_check)
table2 = do.call(rbind.data.frame, answer)
colnames(table2) <- c('GPA below cutoff (1)', 'P-Value (1)', 'Std.err (1)','Intercept (0)', 'P-Value (0)', 'Std.err (0)')
rownames(table2) <- myvars
formattable(table2, 
            align =c("c","c","c","c","c", "c"), 
            list(`Indicator Name` = formatter(
              "span", style = ~ style(color = "grey",font.weight = "bold")),
              `P-Value (1)`= color_tile('pink', 'lightgreen')))
```
#RDD Analysis
##creating subsets 
```{r}
hsg_gr_med <- subset(data1, hsgrade_pct>50)
hsg_ls_med <- subset(data1, hsgrade_pct<=50)
male_data <- subset(data1, male==1)
female_data <- subset(data1,male==0)
Eng_data <- subset(data1,english==1)
noeng_data <- subset(data1,noenglish==1)

Data_sets <- list(data1,hsg_gr_med,hsg_ls_med,male_data,female_data,Eng_data, noeng_data)
```

# RDD Analysis
# left-school
```{r}
left_school_fn = function(x)
{
  model3 = lm(left_school ~ gpalscutoff + gpaXgpalscutoff + gpaXgpagrcutoff, data = x)
  a = coeftest(model3, vcov = vcovCL, cluster = x$clustervar) #other attributes and clustervar removed
  c(a[2,1], a[2, 4], a[2, 2], a[1, 1], a[1, 4], a[1, 2])
}

myvars = c('All Data', 'HSgrade above Median','HSgrade below Median','Male','Female','Eng 1st language', 'Eng not 1st language')

colnames = c('gpa below cutoff 1', 'p-value 1', 'sd-error 1', 'intercept 0', 'p value 0', 'sd-error 1')

answer = lapply(Data_sets, left_school_fn)
table4 = do.call(rbind.data.frame, answer)
colnames(table4) <- c('GPA below cutoff (1)', 'P-Value (1)', 'Std.err (1)','Intercept (0)', 'P-Value (0)', 'Std.err (0)')
rownames(table4) <- myvars
formattable(table4, 
            align =c("c","c","c","c","c", "c"), 
            list(`Indicator Name` = formatter(
              "span", style = ~ style(color = "grey",font.weight = "bold")),
              `P-Value (1)`= color_tile('pink', 'lightgreen')))
```



```{r}
grad6_fn = function(x)
{
  model4 = lm(gradin6 ~ gpalscutoff + gpaXgpalscutoff + gpaXgpagrcutoff, data = x)
  a = coeftest(model4, vcov = vcovCL, cluster = x$clustervar) #other attributes and clustervar removed
  c(a[2,1], a[2, 4], a[2, 2], a[1, 1], a[1, 4], a[1, 2])
}

myvars = c('All Data', 'HSgrade above Median','HSgrade below Median','Male','Female','Eng 1st language', 'Eng not 1st language')

colnames = c('gpa below cutoff 1', 'p-value 1', 'sd-error 1', 'intercept 0', 'p value 0', 'sd-error 1')

answer = lapply(Data_sets, grad6_fn)
table5 = do.call(rbind.data.frame, answer)
colnames(table5) <- c('GPA below cutoff (1)', 'P-Value (1)', 'Std.err (1)','Intercept (0)', 'P-Value (0)', 'Std.err (0)')
rownames(table5) <- myvars
formattable(table5, 
            align =c("c","c","c","c","c", "c"), 
            list(`Indicator Name` = formatter(
              "span", style = ~ style(color = "grey",font.weight = "bold")),
              `P-Value (1)`= color_tile('pink', 'lightgreen')))
```
#RDD Analysis 
#Next GPA 

```{r}
nextGPA_fn = function(x)
{
  model5 = lm(nextGPA ~ gpalscutoff + gpaXgpalscutoff + gpaXgpagrcutoff, data = x)
  a = coeftest(model5, vcov = vcovCL, cluster = x$clustervar) #other attributes and clustervar removed
  c(a[2,1], a[2, 4], a[2, 2], a[1, 1], a[1, 4], a[1, 2])
}

answer = lapply(Data_sets, nextGPA_fn)
table6 = do.call(rbind.data.frame, answer)
colnames(table6) <- c('GPA below cutoff (1)', 'P-Value (1)', 'Std.err (1)','Intercept (0)', 'P-Value (0)', 'Std.err (0)')
rownames(table6) <- myvars
formattable(table6, 
            align =c("c","c","c","c","c", "c"), 
            list(`Indicator Name` = formatter(
              "span", style = ~ style(color = "grey",font.weight = "bold")),
              `P-Value (1)`= color_tile('pink', 'lightgreen')))
```

